from __future__ import annotations

from pathlib import Path
from typing import Protocol


class Runner(Protocol):
    async def observe(self, observation_id: int, ms_path: Path, log_path: Path) -> int: ...
    async def process(self, observation_id: int, run_id: int, ms_path: Path, output_prefix: Path, log_path: Path) -> int: ...
    async def abort_observation(self, observation_id: int) -> None: ...
    async def kill_managed(self) -> None: ...
